import Head from 'next/head'
import AboutUsSection from '../components/AboutUs'
import IntroSection from '../components/Intro'
import PublicMintSection from '../components/PublicMint'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wishmaco.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntroSection />
      <PublicMintSection />
      <AboutUsSection />
    </div>
  )
}
