import Head from 'next/head'
import Image from 'next/image'
import IntroSection from '../components/Intro'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wishmaco.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntroSection/>
      
    </div>
  )
}
 