module.exports = {
    "headshot1": '/headshot1.png',
    "headshot2": '/headshot2.png',
    "headshot3": '/headshot3.png',
    "headshot4": '/headshot4.png',
    "headshot5": '/headshot5.png',
    "noSelfieIcon": '/noSelfieIcon.png',
    "happyMood": '/happyMood.png',
    "disgustMood": '/disgustMood.png',
    "sadMood": '/sadMood.png',
    'angryMood': '/angryMood.png',
    'showMood': '/showMood.png',
    'noneMood': '/noneMood.png',
    'headShotPlaceHolder': '/headShotPlaceHolder.png',
}